export default {
  Logo: require("../../assets/images/Logo.png"),
  EyeOn: require("../../assets/images/eyeOn.png"),
  EyeOff: require("../../assets/images/eyeOff.png"),
  Home: require("../../assets/images/home.png"),
  LuaraIa: require("../../assets/images/lauraia.png"),
  Profile: require("../../assets/images/photo.png"),
  logoSplash: require("../../assets/images/LogoSplash.png"),
  Onboarding1: require("../../assets/images/Onboarding1.png"),
  Onboarding2: require("../../assets/images/Onboarding2.png"),
  Onboarding3: require("../../assets/images/Onboarding3.png"),
  Frame: require("../../assets/images/Frame.png"),
  robo: require("../../assets/images/robo.png"),
  User: require("../../assets/images/robo.png"),
  AvatarTereza: require("../../assets/images/avatarRobo.png"),
}
